In [1]:
import torch

In [2]:
x = torch.arange(10)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [3]:
x[-1] = 100
print(x[2], x[-1], sep="\n")

tensor(2)
tensor(100)


In [4]:
x = torch.arange(10).reshape(2, 5)
print(x)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [5]:
print(x[1, 2], x[0, -1], sep="\n")

tensor(7)
tensor(4)


In [6]:
y = torch.zeros(size=(2, 3, 4))
y[1, 0, 0] = -2
y[-1, -1, -1] = 1
print(y)

tensor([[[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]],

        [[-2.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  1.]]])


In [7]:
y[1, 1:2, 0:4:2] = 100
print(y)

tensor([[[  0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.]],

        [[ -2.,   0.,   0.,   0.],
         [100.,   0., 100.,   0.],
         [  0.,   0.,   0.,   1.]]])


In [8]:
print(y[y > 0])

tensor([100., 100.,   1.])


In [9]:
z = y > 0
print(z, y[z], sep="\n")

tensor([[[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]],

        [[False, False, False, False],
         [ True, False,  True, False],
         [False, False, False,  True]]])
tensor([100., 100.,   1.])


In [11]:
print(y[[False, True]])

tensor([[[ -2.,   0.,   0.,   0.],
         [100.,   0., 100.,   0.],
         [  0.,   0.,   0.,   1.]]])


In [12]:
# Generate a 10x10 tensor with normally distributed random values
X = torch.randn(10, 10)

# Create a tensor Y filled with Inf values
Y = torch.full_like(X, float('inf'))

# Replace negative values in X with Inf using torch.where()
X_modified = torch.where(X < 0, Y, X)

# Print the result
print(X_modified)

tensor([[2.2262,    inf, 1.9437, 1.2978,    inf, 0.0425,    inf,    inf,    inf,
            inf],
        [0.2567, 0.6321, 0.8066,    inf,    inf,    inf, 1.8823,    inf, 0.8868,
            inf],
        [   inf,    inf,    inf,    inf, 1.1582,    inf,    inf,    inf, 1.9341,
            inf],
        [   inf, 0.0281,    inf, 1.6257,    inf, 1.2384, 1.1864, 1.3153,    inf,
            inf],
        [   inf,    inf,    inf, 0.7576,    inf, 0.2093, 0.6127, 0.2703, 0.8654,
         1.2049],
        [   inf,    inf, 2.4006,    inf,    inf,    inf, 0.3412, 1.1782, 0.5925,
            inf],
        [0.3202,    inf, 0.8843,    inf, 1.9705,    inf, 0.6319, 1.3081, 0.7467,
         0.3043],
        [   inf,    inf,    inf, 1.0291,    inf, 0.2788,    inf, 0.3288, 1.4740,
         0.1886],
        [0.1616, 0.8553,    inf, 1.0598,    inf, 0.1604, 0.7347,    inf,    inf,
            inf],
        [0.4660, 0.6498,    inf,    inf, 0.6042, 0.3533, 1.7318, 0.9686,    inf,
            inf]])


In [13]:
# Generate a 3D tensor (10,5,2) with random normal values
X_3D = torch.randn(10, 5, 2)

# Create a tensor of Inf values with the same shape
Y_3D = torch.full_like(X_3D, float('inf'))

# Find indices where all three dimensions are odd
indices = torch.where((torch.arange(10) % 2 == 1)[:, None, None] &
                      (torch.arange(5) % 2 == 1)[None, :, None] &
                      (torch.arange(2) % 2 == 1)[None, None, :])

# Assign Inf to these indices
X_3D[indices] = float('inf')

# Print the modified tensor
print(X_3D)

tensor([[[-0.0862, -0.5764],
         [ 0.6689, -0.3803],
         [ 0.9414,  0.4945],
         [-0.6924, -2.4997],
         [-1.0520,  0.0505]],

        [[ 0.8466,  0.6332],
         [ 0.5571,     inf],
         [ 1.0363,  0.1990],
         [-0.8376,     inf],
         [-0.8878, -0.7852]],

        [[-0.0731,  0.8435],
         [ 0.7498, -1.0367],
         [ 1.2827, -1.6611],
         [-2.1193,  0.8852],
         [ 2.1563,  0.9143]],

        [[-0.6431, -1.5401],
         [-2.2609,     inf],
         [-0.1842, -0.2198],
         [ 0.2980,     inf],
         [ 0.0884,  1.6475]],

        [[ 0.2215,  0.2504],
         [-0.1141, -0.6391],
         [-0.5330,  0.9913],
         [-0.8952,  0.5848],
         [-1.2092, -0.8076]],

        [[-1.9640,  0.4835],
         [-0.9802,     inf],
         [ 0.3634, -0.7121],
         [ 1.0765,     inf],
         [ 1.0097, -0.2279]],

        [[ 0.6394, -0.4369],
         [ 0.0055,  0.0783],
         [ 0.3814,  0.9512],
         [-0.8720,  0.3665],
  