In [1]:
import torch

In [2]:
x = torch.tensor([2.], requires_grad=True)

In [3]:
y = x ** 2
z = y + x
z.backward(x.grad)
print(x.grad)

tensor([5.])


In [4]:
x = torch.tensor([2., 3.], requires_grad=True)
y = x[0] * x[1]
y.backward()
print(x.grad)

tensor([3., 2.])


In [8]:
x = torch.tensor([2., 3.], requires_grad=True)
y = torch.tensor([4., 5.], requires_grad=True)
w = x.sum() ** 2
z = w + y.sum() ** 3 + x[0] + y[1]
z.backward()
print(x.grad, y.grad, sep="\n")

tensor([11., 10.])
tensor([243., 244.])


In [9]:
x = torch.tensor([2., 3.], requires_grad=True)
y = torch.tensor([4., 5.], requires_grad=True)
w = x.sum() ** 2
s = w.detach()
z = s + y.sum() ** 3 + x[0] + y[1]
z.backward()
print(x.grad, y.grad, sep="\n")

tensor([1., 0.])
tensor([243., 244.])


In [10]:
y = torch.zeros(10, dtype=int)
x = torch.tensor([2.], requires_grad=True)
for i in range(10):
    z = 2 * x
    while torch.rand(1) < 0.7:
        z = 2 * z
    z.backward()
    y[i] = x.grad
    x.grad = None
print(y)

tensor([ 8,  2,  4,  8,  2,  2,  4,  2,  4, 16])


In [11]:
y = torch.zeros(5)
for i in range(5):
    x = torch.randn(1, requires_grad=True)
    if x > 0:
        z = torch.exp(x)
    else:
        z = -x
    z.backward()
    y[i] = x.grad
print(y)

tensor([ 2.0854, -1.0000, -1.0000,  8.4896, -1.0000])
