In [1]:
import torch

In [2]:
x = torch.tensor([[1, 2], [3, 4]])
print(x, x.shape, x.dtype, sep="\n")

tensor([[1, 2],
        [3, 4]])
torch.Size([2, 2])
torch.int64


In [3]:
x = torch.tensor([[1.0, 2, 3, 4]])
print(x, x.shape, x.dtype, sep="\n")

tensor([[1., 2., 3., 4.]])
torch.Size([1, 4])
torch.float32


In [4]:
x = torch.arange(9)
y = torch.eye(3, dtype=torch.bool)
z = torch.randn(size=[2, 3, 3])
print(x, y, z, sep="\n")

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
tensor([[ True, False, False],
        [False,  True, False],
        [False, False,  True]])
tensor([[[-0.0786, -0.1318,  1.0704],
         [ 1.3142,  1.6130,  1.1816],
         [-1.9288,  1.1005, -0.1828]],

        [[ 1.6282, -1.3232, -0.0917],
         [ 1.4285,  0.8675, -0.2012],
         [-0.3579,  0.7554,  0.9783]]])


In [5]:
mixed_list = [42, 3.14, 'a', True]
try:
    tensor = torch.tensor(mixed_list)
    print(tensor)
except Exception as e:
    print(f"Error: {e}")

x = torch.tensor([1, 2.0, True, False])
print(x)

Error: new(): invalid data type 'str'
tensor([1., 2., 1., 0.])


In [6]:
bit_tensor = torch.randint(low=0, high=2, size=(2, 3, 4, 5), dtype=torch.uint8)
print(bit_tensor)

tensor([[[[1, 0, 0, 0, 1],
          [1, 1, 0, 1, 1],
          [0, 1, 0, 0, 0],
          [0, 0, 1, 0, 1]],

         [[0, 1, 0, 0, 1],
          [1, 1, 1, 1, 0],
          [1, 1, 0, 1, 0],
          [1, 0, 0, 0, 1]],

         [[0, 0, 0, 1, 0],
          [1, 0, 0, 1, 1],
          [0, 0, 0, 1, 1],
          [0, 0, 1, 0, 1]]],


        [[[0, 1, 1, 1, 0],
          [0, 1, 0, 0, 1],
          [0, 0, 1, 0, 1],
          [1, 0, 0, 1, 1]],

         [[0, 1, 1, 0, 0],
          [0, 1, 1, 0, 1],
          [0, 0, 0, 1, 0],
          [0, 1, 1, 1, 1]],

         [[0, 1, 0, 1, 1],
          [0, 1, 1, 1, 0],
          [0, 1, 0, 1, 1],
          [1, 1, 1, 0, 0]]]], dtype=torch.uint8)
