In [1]:
import torch

In [2]:
x = torch.tensor([1, 2, 3, 4])
print(x == 1)

tensor([ True, False, False, False])


In [3]:
y = torch.tensor([1] * x.numel())
print(x, y, x == y, sep="\n")

tensor([1, 2, 3, 4])
tensor([1, 1, 1, 1])
tensor([ True, False, False, False])


In [4]:
A = torch.arange(9).reshape(3, 3)
B = torch.arange(3)
print(A, B, A + B, sep="\n")

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([0, 1, 2])
tensor([[ 0,  2,  4],
        [ 3,  5,  7],
        [ 6,  8, 10]])


In [5]:
B.expand_as(A)

tensor([[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]])

In [6]:
B.reshape(3, 1).expand_as(A)

tensor([[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]])

In [7]:
A = torch.arange(3).reshape(3, 1)
B = torch.arange(4).reshape(1, 4)
print(A, B, A + B, sep="\n")

tensor([[0],
        [1],
        [2]])
tensor([[0, 1, 2, 3]])
tensor([[0, 1, 2, 3],
        [1, 2, 3, 4],
        [2, 3, 4, 5]])


In [8]:
A = torch.arange(6).reshape(3, 2)
B = torch.arange(5).reshape(1, 5)
print(A, B, sep="\n")

tensor([[0, 1],
        [2, 3],
        [4, 5]])
tensor([[0, 1, 2, 3, 4]])


In [9]:
A + B

RuntimeError: The size of tensor a (2) must match the size of tensor b (5) at non-singleton dimension 1

In [10]:
A = torch.arange(24).reshape(2, 3, 4)
B = torch.tensor([0, 1, 2, 3])
C = B.expand_as(A)
D = A + B
print(A.size(), B.size(), C, D, sep="\n")

torch.Size([2, 3, 4])
torch.Size([4])
tensor([[[0, 1, 2, 3],
         [0, 1, 2, 3],
         [0, 1, 2, 3]],

        [[0, 1, 2, 3],
         [0, 1, 2, 3],
         [0, 1, 2, 3]]])
tensor([[[ 0,  2,  4,  6],
         [ 4,  6,  8, 10],
         [ 8, 10, 12, 14]],

        [[12, 14, 16, 18],
         [16, 18, 20, 22],
         [20, 22, 24, 26]]])


In [ ]:
# C[i, j, k] == B[k]
C[1, 2, 3] == B[3]

tensor(True)

In [ ]:
# A. Pairs that can be broadcasted:
# (C, D) → (5×5)
# (C, E) → (5×1)
# (D, E) → (1×5)
# (C, F) → (5×3)
# B. Resulting shape of the valid broadcasting pairs:
# (C, D) → (5×5)
# (C, E) → (5×1)
# (D, E) → (1×5)
# (C, F) → (5×3)