In [1]:
import torch

In [2]:
x = torch.tensor([1, 2, 3, 4])
y = torch.tensor([5, 6, 7, 8])
print(x + y, x - y, x * y, x / y, x ** y, sep="\n")

tensor([ 6,  8, 10, 12])
tensor([-4, -4, -4, -4])
tensor([ 5, 12, 21, 32])
tensor([0.2000, 0.3333, 0.4286, 0.5000])
tensor([    1,    64,  2187, 65536])


In [3]:
%%timeit
x * y

988 ns ± 25.8 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [4]:
%%timeit
for i in range(x.numel()):
    x[i] * y[i]

12.3 μs ± 205 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [5]:
x = torch.tensor([1, 2, 3, 4])
y = torch.tensor([5, 6, 7, 8])
print(x @ y, x == 1, sep="\n")

tensor(70)
tensor([ True, False, False, False])


In [6]:
x = x.reshape(1, 4)
y = y.reshape(4, 1)
print(x, y, x @ y, y @ x, sep="\n")

tensor([[1, 2, 3, 4]])
tensor([[5],
        [6],
        [7],
        [8]])
tensor([[70]])
tensor([[ 5, 10, 15, 20],
        [ 6, 12, 18, 24],
        [ 7, 14, 21, 28],
        [ 8, 16, 24, 32]])


In [7]:
x = torch.ones(size=(3,))
y = torch.ones(size=(3, 3))
z = torch.ones(size=(3, 3, 3))
print(x.norm(), y.min(), z.sum(), sep="\n")

tensor(1.7321)
tensor(1.)
tensor(27.)


In [9]:
x = torch.arange(24).reshape(2, 3, 4)
print(x, x.size())

y = x.sum()
print(y, y.size())

z = x.sum(axis=0)
print(z, z.size())

w = x.sum(axis=1)
print(w, w.size())

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]) torch.Size([2, 3, 4])
tensor(276) torch.Size([])
tensor([[12, 14, 16, 18],
        [20, 22, 24, 26],
        [28, 30, 32, 34]]) torch.Size([3, 4])
tensor([[12, 15, 18, 21],
        [48, 51, 54, 57]]) torch.Size([2, 4])


In [12]:
# A. Create a 3D tensor of size 100x2x2 with random values from a uniform standard distribution
tensor = torch.rand(100, 2, 2)
print(tensor)

tensor([[[8.0278e-01, 1.0759e-01],
         [4.0118e-01, 4.8217e-01]],

        [[2.4938e-01, 7.5907e-01],
         [2.7965e-01, 2.4812e-01]],

        [[3.1515e-01, 5.4858e-01],
         [2.2857e-01, 9.5553e-01]],

        [[4.4682e-01, 9.8151e-01],
         [6.0814e-01, 6.2560e-01]],

        [[9.3002e-01, 5.9698e-01],
         [8.2980e-01, 4.5499e-01]],

        [[2.3769e-01, 5.1666e-01],
         [1.7043e-01, 2.4850e-01]],

        [[4.4819e-01, 4.8414e-01],
         [1.7625e-01, 3.1510e-01]],

        [[3.6484e-01, 7.2267e-01],
         [7.5203e-02, 3.1234e-01]],

        [[7.0786e-01, 5.0696e-01],
         [2.8431e-01, 7.1814e-01]],

        [[9.9901e-02, 8.1041e-01],
         [1.5602e-01, 6.4458e-01]],

        [[2.6676e-01, 6.4232e-01],
         [4.5194e-01, 7.2129e-01]],

        [[6.0633e-01, 3.2993e-01],
         [7.3408e-01, 5.0767e-01]],

        [[9.8968e-01, 4.8175e-01],
         [3.0960e-01, 7.2097e-01]],

        [[2.1431e-01, 7.9854e-01],
         [9.2870e-01, 7.5538e

In [13]:
# Compute the eigenvalues for each 2x2 matrix along the last dimension
eigenvalues = torch.linalg.eigvals(tensor)
print(eigenvalues)

tensor([[ 0.9049+0.j,  0.3801+0.j],
        [ 0.7095+0.j, -0.2120+0.j],
        [ 0.1579+0.j,  1.1127+0.j],
        [-0.2415+0.j,  1.3140+0.j],
        [ 1.4353+0.j, -0.0503+0.j],
        [-0.0537+0.j,  0.5399+0.j],
        [ 0.6812+0.j,  0.0821+0.j],
        [ 0.5732+0.j,  0.1040+0.j],
        [ 0.3333+0.j,  1.0927+0.j],
        [-0.0757+0.j,  0.8201+0.j],
        [-0.0907+0.j,  1.0788+0.j],
        [ 1.0516+0.j,  0.0624+0.j],
        [ 1.2642+0.j,  0.4464+0.j],
        [-0.4178+0.j,  1.3875+0.j],
        [-0.6762+0.j,  0.9588+0.j],
        [ 0.6963+0.j, -0.0487+0.j],
        [ 1.8218+0.j, -0.0560+0.j],
        [ 0.4390+0.j,  1.3161+0.j],
        [ 0.1973+0.j,  0.4023+0.j],
        [-0.0768+0.j,  1.3927+0.j],
        [ 0.4459+0.j,  1.1911+0.j],
        [ 1.3115+0.j,  0.2459+0.j],
        [ 0.7697+0.j, -0.1623+0.j],
        [-0.0984+0.j,  0.7220+0.j],
        [ 0.0099+0.j,  0.7955+0.j],
        [ 0.4904+0.j,  1.2014+0.j],
        [-0.1481+0.j,  0.6572+0.j],
        [ 0.2424+0.j,  0.621

In [14]:
# Check the imaginary part of the eigenvalues
imaginary_parts = eigenvalues.imag
print(imaginary_parts)

max_imaginary = imaginary_parts.abs().max()
print(f"Example eigenvalues:\n {eigenvalues[:,:,0]}")
print(f"Maximum imaginary part: {max_imaginary}")

# Explanation: Since the matrices are generated with random values from a uniform distribution,
# they are not necessarily symmetric. Non-symmetric matrices can have complex eigenvalues
# (i.e., eigenvalues with a nonzero imaginary component).

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0

IndexError: too many indices for tensor of dimension 2

In [15]:
# B. Compute the Frobenius norm for each 2x2 matrix
frobenius_norms = torch.linalg.norm(tensor, dim=(0, 1))
print(f"Example Frobenius norm: {frobenius_norms[0]}")

Example Frobenius norm: 8.170580863952637


In [16]:
# C. Compute the Euclidean norm of the entire tensor, considering all its values
euclidean_norm = torch.linalg.norm(tensor)
print(f"Euclidean norm of the full tensor: {euclidean_norm}")

Euclidean norm of the full tensor: 11.379456520080566


In [20]:
# D. Infinty norm of a 100x2 matrix
inf_norms = torch.linalg.norm(tensor.reshape(200, 2), ord=torch.inf, dim=1)
print(f"Infinity norms: {inf_norms}")

Infinity norms: tensor([0.8028, 0.4822, 0.7591, 0.2797, 0.5486, 0.9555, 0.9815, 0.6256, 0.9300,
        0.8298, 0.5167, 0.2485, 0.4841, 0.3151, 0.7227, 0.3123, 0.7079, 0.7181,
        0.8104, 0.6446, 0.6423, 0.7213, 0.6063, 0.7341, 0.9897, 0.7210, 0.7985,
        0.9287, 0.7420, 0.8974, 0.3572, 0.3856, 0.9117, 0.9736, 0.7575, 0.9976,
        0.2093, 0.3903, 0.4897, 0.9974, 0.7541, 0.8829, 0.9532, 0.6042, 0.5108,
        0.5734, 0.2281, 0.6589, 0.7851, 0.6001, 0.7540, 0.9377, 0.2551, 0.5344,
        0.4051, 0.6194, 0.4397, 0.4431, 0.4113, 0.8769, 0.9649, 0.9103, 0.5182,
        0.6830, 0.8296, 0.8888, 0.8644, 0.9369, 0.8653, 0.4832, 0.9805, 0.6931,
        0.8429, 0.9117, 0.2050, 0.7018, 0.2187, 0.7093, 0.1184, 0.5163, 0.8062,
        0.1906, 0.7654, 0.8035, 0.7879, 0.2174, 0.9049, 0.5660, 0.7504, 0.9060,
        0.8715, 0.6932, 0.5998, 0.5057, 0.6163, 0.7207, 0.1946, 0.1635, 0.6847,
        0.9484, 0.9542, 0.8170, 0.6486, 0.9219, 0.9714, 0.8828, 0.6903, 0.4592,
        0.8137, 0.9940, 

In [22]:
%%timeit
# Extract two 2x100 matrices
matrix1 = tensor[0]  # Shape (2, 100)
matrix2 = tensor[1]  # Shape (2, 100)

# Compute infinity norms in a single operation
inf_norm1 = torch.linalg.norm(matrix1, ord=torch.inf, dim=1)
inf_norm2 = torch.linalg.norm(matrix2, ord=torch.inf, dim=1)

6.7 μs ± 118 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [23]:
%%timeit
inf_norm1_loop = torch.empty(2)
inf_norm2_loop = torch.empty(2)

# Loop through each row manually (less efficient)
for i in range(2):
    inf_norm1_loop[i] = torch.linalg.norm(tensor[0][i], ord=torch.inf)
    inf_norm2_loop[i] = torch.linalg.norm(tensor[1][i], ord=torch.inf)

24.5 μs ± 679 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
